// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUCI1EBrkPL2EG6shyWQdjBDwnYncTaLU',
    appId: '1:742813579430:web:a70f419ec691faac841c67',
    messagingSenderId: '742813579430',
    projectId: 'chatapp2-25e8e',
    authDomain: 'chatapp2-25e8e.firebaseapp.com',
    storageBucket: 'chatapp2-25e8e.firebasestorage.app',
    measurementId: 'G-0ETQW5VB68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF-tRTSg1YDzXS34FCmzxqplCYzJCviW4',
    appId: '1:742813579430:android:a786af712ee4fbca841c67',
    messagingSenderId: '742813579430',
    projectId: 'chatapp2-25e8e',
    storageBucket: 'chatapp2-25e8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0SyLlXvVjH8bZsQuV-TvZSLTVPstSUTw',
    appId: '1:178669994094:ios:ac5697b47bea7f215c667f',
    messagingSenderId: '178669994094',
    projectId: 'chat-app-f1e2e',
    storageBucket: 'chat-app-f1e2e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0SyLlXvVjH8bZsQuV-TvZSLTVPstSUTw',
    appId: '1:178669994094:ios:ac5697b47bea7f215c667f',
    messagingSenderId: '178669994094',
    projectId: 'chat-app-f1e2e',
    storageBucket: 'chat-app-f1e2e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUCI1EBrkPL2EG6shyWQdjBDwnYncTaLU',
    appId: '1:742813579430:web:2b2226bc6608b3f2841c67',
    messagingSenderId: '742813579430',
    projectId: 'chatapp2-25e8e',
    authDomain: 'chatapp2-25e8e.firebaseapp.com',
    storageBucket: 'chatapp2-25e8e.firebasestorage.app',
    measurementId: 'G-7F1KMHVVQ5',
  );

}